// @vitest-environment jsdom

import { afterEach, beforeEach, describe, expect, it, vi } from "vitest";

import i18n from "@/i18n/bootstrapI18n";

import { exportMultiToCSV, exportMultiToPDF } from "./multi_export_utils";
import type { CostEstimateResponse } from "../types";
import type { MultiModelResult } from "./types";

vi.mock("@/utils/dataUtils", () => ({
  formatNumberWithCommas: vi.fn((v: number, d: number = 0) => (Number.isFinite(v) ? v.toFixed(d) : "-")),
}));

const t = i18n.getFixedT("zh", "costTracking");

function makeCostResponse(overrides: Partial<CostEstimateResponse> = {}): CostEstimateResponse {
  return {
    model: "gpt-4",
    input_tokens: 1000,
    output_tokens: 500,
    num_requests_per_day: 100,
    num_requests_per_month: 3000,
    cost_per_request: 0.05,
    input_cost_per_request: 0.03,
    output_cost_per_request: 0.02,
    margin_cost_per_request: 0.01,
    daily_cost: 5.0,
    daily_input_cost: 3.0,
    daily_output_cost: 2.0,
    daily_margin_cost: 1.0,
    monthly_cost: 150.0,
    monthly_input_cost: 90.0,
    monthly_output_cost: 60.0,
    monthly_margin_cost: 30.0,
    input_cost_per_token: 0.00003,
    output_cost_per_token: 0.00004,
    provider: "openai",
    ...overrides,
  };
}

function makeMultiResult(models: number = 1): MultiModelResult {
  return {
    entries: Array.from({ length: models }, (_, index) => ({
      entry: { id: `e${index}`, model: "gpt-4", input_tokens: 1000, output_tokens: 500 },
      result: makeCostResponse(),
      loading: false,
      error: null,
    })),
    totals: {
      cost_per_request: 0.05,
      daily_cost: 5.0,
      monthly_cost: 150.0,
      margin_per_request: 0.01,
      daily_margin: 1.0,
      monthly_margin: 30.0,
    },
  };
}

let mockPrintWindow: {
  document: { write: ReturnType<typeof vi.fn>; close: ReturnType<typeof vi.fn> };
  print: ReturnType<typeof vi.fn>;
  onload: (() => void) | null;
};

const writtenHtml = (): string => mockPrintWindow.document.write.mock.calls[0][0] as string;

const capturedCsv = (): string => {
  let csv = "";
  const OriginalBlob = globalThis.Blob;
  globalThis.Blob = class extends OriginalBlob {
    constructor(parts?: BlobPart[], options?: BlobPropertyBag) {
      super(parts, options);
      if (typeof parts?.[0] === "string") csv = parts[0];
    }
  } as unknown as typeof Blob;
  exportMultiToCSV(makeMultiResult(), t);
  globalThis.Blob = OriginalBlob;
  return csv;
};

describe("multi export utilities Chinese copy", () => {
  beforeEach(() => {
    vi.clearAllMocks();
    vi.spyOn(Date.prototype, "toLocaleString").mockReturnValue("2026/9/18 10:00:00");
    mockPrintWindow = { document: { write: vi.fn(), close: vi.fn() }, print: vi.fn(), onload: null };
    vi.spyOn(window, "open").mockReturnValue(mockPrintWindow as unknown as Window);
    window.URL.createObjectURL = vi.fn(() => "blob:mock-url");
    window.URL.revokeObjectURL = vi.fn();
  });

  afterEach(async () => {
    vi.restoreAllMocks();
    await i18n.changeLanguage("en");
  });

  it("renders the Chinese popup-blocked alert", () => {
    vi.spyOn(window, "open").mockReturnValue(null);
    const alertSpy = vi.spyOn(window, "alert").mockImplementation(() => {});

    exportMultiToPDF(makeMultiResult(), t);

    expect(alertSpy).toHaveBeenCalledWith("请允许弹出窗口以导出 PDF");
    expect(alertSpy).not.toHaveBeenCalledWith("Please allow popups to export PDF");
  });

  it("renders the Chinese PDF report headings and summary labels", () => {
    exportMultiToPDF(makeMultiResult(), t);
    const html = writtenHtml();

    expect(html).toContain("<title>多模型成本估算报告</title>");
    expect(html).not.toContain("<title>Multi-Model Cost Estimate Report</title>");
    expect(html).toContain("<h1>LLM 成本估算报告</h1>");
    expect(html).not.toContain("<h1>LLM Cost Estimate Report</h1>");
    expect(html).toContain(">已配置 1 个模型<");
    expect(html).not.toContain("1 model configured");
    expect(html).toContain("<h2>合计</h2>");
    expect(html).not.toContain("<h2>Combined Totals</h2>");
    expect(html).toContain(">每请求总计<");
    expect(html).toContain(">每日总计<");
    expect(html).toContain(">每月总计<");
    expect(html).toContain(">每请求加价<");
    expect(html).toContain(">每日加价<");
    expect(html).toContain(">每月加价<");
    expect(html).not.toContain("Total Per Request");
    expect(html).not.toContain(">Total Daily<");
    expect(html).not.toContain(">Total Monthly<");
    expect(html).not.toContain(">Margin/Request<");
    expect(html).not.toContain(">Daily Margin<");
    expect(html).not.toContain(">Monthly Margin<");
    expect(html).toContain("<h2>模型明细</h2>");
    expect(html).not.toContain("<h2>Model Breakdown</h2>");
    expect(html).toContain(">由 LiteLLM 定价计算器于 2026/9/18 10:00:00 生成<");
    expect(html).not.toContain("Generated by LiteLLM Pricing Calculator on");
  });

  it("renders the Chinese model count for multiple models", () => {
    exportMultiToPDF(makeMultiResult(2), t);
    const html = writtenHtml();

    expect(html).toContain(">已配置 2 个模型<");
    expect(html).not.toContain("2 models configured");
  });

  it("renders the Chinese per-model breakdown table", () => {
    exportMultiToPDF(makeMultiResult(), t);
    const html = writtenHtml();

    expect(html).toContain(">每请求输入 Token：<");
    expect(html).toContain(">每请求输出 Token：<");
    expect(html).toContain(">每天请求数：<");
    expect(html).toContain(">每月请求数：<");
    expect(html).toContain(">成本类型<");
    expect(html).toContain(">每请求<");
    expect(html).toContain(">每日<");
    expect(html).toContain(">每月<");
    expect(html).toContain(">输入成本<");
    expect(html).toContain(">输出成本<");
    expect(html).toContain(">加价/费用<");
    expect(html).toContain(">总计<");

    expect(html).not.toContain("Input Tokens per Request:");
    expect(html).not.toContain("Output Tokens per Request:");
    expect(html).not.toContain("Requests per Day:");
    expect(html).not.toContain("Requests per Month:");
    expect(html).not.toContain("Cost Type");
    expect(html).not.toContain(">Per Request<");
    expect(html).not.toContain(">Input Cost<");
    expect(html).not.toContain(">Output Cost<");
    expect(html).not.toContain(">Margin/Fee<");
    expect(html).not.toContain(">Total<");
  });

  it("renders the Chinese CSV report title, metadata and summary rows", () => {
    const csv = capturedCsv();

    expect(csv).toContain('"LLM 多模型成本估算报告"');
    expect(csv).not.toContain('"LLM Multi-Model Cost Estimate Report"');
    expect(csv).toContain('"生成时间","2026/9/18 10:00:00"');
    expect(csv).not.toContain('"Generated"');
    expect(csv).toContain('"合计"');
    expect(csv).not.toContain('"COMBINED TOTALS"');
    expect(csv).toContain('"每请求总计"');
    expect(csv).toContain('"每日总计"');
    expect(csv).toContain('"每月总计"');
    expect(csv).toContain('"每请求加价"');
    expect(csv).toContain('"每日加价"');
    expect(csv).toContain('"每月加价"');
    expect(csv).not.toContain('"Total Per Request"');
    expect(csv).not.toContain('"Margin Per Request"');
    expect(csv).not.toContain('"Daily Margin"');
    expect(csv).not.toContain('"Monthly Margin"');
  });

  it("renders the Chinese CSV table header row", () => {
    const csv = capturedCsv();

    expect(csv).toContain(
      '"模型","提供商","输入 Token","输出 Token","请求数/天","请求数/月","每请求成本","每日成本","每月成本","每请求输入成本","每请求输出成本","每请求加价"',
    );
    expect(csv).not.toContain(
      '"Model","Provider","Input Tokens","Output Tokens","Requests/Day","Requests/Month","Cost/Request","Daily Cost","Monthly Cost","Input Cost/Req","Output Cost/Req","Margin/Req"',
    );
  });
});
