import type { ParseKeys } from "i18next";
import { guardrailLogoMap } from "./guardrail_info_helpers";

export interface GuardrailCardInfo {
  id: string;
  nameKey: ParseKeys<"guardrails">;
  descriptionKey: ParseKeys<"guardrails">;
  category: "litellm" | "partner";
  subcategoryKey?: ParseKeys<"guardrails">;
  logo: string;
  tagKeys: ReadonlyArray<ParseKeys<"guardrails">>;
  eval?: {
    f1: number;
    precision: number;
    recall: number;
    testCases: number;
    latency: string;
  };
  providerKey?: string;
}

const litellmContentFilterLogo = guardrailLogoMap["LiteLLM Content Filter"];

export const LITELLM_CONTENT_FILTER_CARDS: GuardrailCardInfo[] = [
  {
    id: "cf_denied_financial",
    nameKey: "garden.cards.cf_denied_financial.name",
    descriptionKey: "garden.cards.cf_denied_financial.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.topicBlocker"],
    eval: {
      f1: 100.0,
      precision: 100.0,
      recall: 100.0,
      testCases: 207,
      latency: "<0.1ms",
    },
  },
  {
    id: "cf_denied_insults",
    nameKey: "garden.cards.cf_denied_insults.name",
    descriptionKey: "garden.cards.cf_denied_insults.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.topicBlocker"],
    eval: {
      f1: 100.0,
      precision: 100.0,
      recall: 100.0,
      testCases: 299,
      latency: "<0.1ms",
    },
  },
  {
    id: "cf_denied_legal",
    nameKey: "garden.cards.cf_denied_legal.name",
    descriptionKey: "garden.cards.cf_denied_legal.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.topicBlocker"],
  },
  {
    id: "cf_denied_medical",
    nameKey: "garden.cards.cf_denied_medical.name",
    descriptionKey: "garden.cards.cf_denied_medical.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.topicBlocker"],
  },
  {
    id: "cf_harmful_violence",
    nameKey: "garden.cards.cf_harmful_violence.name",
    descriptionKey: "garden.cards.cf_harmful_violence.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.safety"],
  },
  {
    id: "cf_harmful_self_harm",
    nameKey: "garden.cards.cf_harmful_self_harm.name",
    descriptionKey: "garden.cards.cf_harmful_self_harm.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.safety"],
  },
  {
    id: "cf_harmful_child_safety",
    nameKey: "garden.cards.cf_harmful_child_safety.name",
    descriptionKey: "garden.cards.cf_harmful_child_safety.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.safety"],
  },
  {
    id: "cf_harmful_illegal_weapons",
    nameKey: "garden.cards.cf_harmful_illegal_weapons.name",
    descriptionKey: "garden.cards.cf_harmful_illegal_weapons.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.safety"],
  },
  {
    id: "cf_bias_gender",
    nameKey: "garden.cards.cf_bias_gender.name",
    descriptionKey: "garden.cards.cf_bias_gender.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.bias"],
  },
  {
    id: "cf_bias_racial",
    nameKey: "garden.cards.cf_bias_racial.name",
    descriptionKey: "garden.cards.cf_bias_racial.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.bias"],
  },
  {
    id: "cf_bias_religious",
    nameKey: "garden.cards.cf_bias_religious.name",
    descriptionKey: "garden.cards.cf_bias_religious.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.bias"],
  },
  {
    id: "cf_bias_sexual_orientation",
    nameKey: "garden.cards.cf_bias_sexual_orientation.name",
    descriptionKey: "garden.cards.cf_bias_sexual_orientation.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.bias"],
  },
  {
    id: "cf_prompt_injection_jailbreak",
    nameKey: "garden.cards.cf_prompt_injection_jailbreak.name",
    descriptionKey: "garden.cards.cf_prompt_injection_jailbreak.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.promptInjection"],
  },
  {
    id: "cf_prompt_injection_data_exfil",
    nameKey: "garden.cards.cf_prompt_injection_data_exfil.name",
    descriptionKey: "garden.cards.cf_prompt_injection_data_exfil.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.promptInjection"],
  },
  {
    id: "cf_prompt_injection_sql",
    nameKey: "garden.cards.cf_prompt_injection_sql.name",
    descriptionKey: "garden.cards.cf_prompt_injection_sql.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.promptInjection"],
  },
  {
    id: "cf_prompt_injection_malicious_code",
    nameKey: "garden.cards.cf_prompt_injection_malicious_code.name",
    descriptionKey: "garden.cards.cf_prompt_injection_malicious_code.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.promptInjection"],
  },
  {
    id: "cf_prompt_injection_system_prompt",
    nameKey: "garden.cards.cf_prompt_injection_system_prompt.name",
    descriptionKey: "garden.cards.cf_prompt_injection_system_prompt.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.promptInjection"],
  },
  {
    id: "cf_toxic_abuse",
    nameKey: "garden.cards.cf_toxic_abuse.name",
    descriptionKey: "garden.cards.cf_toxic_abuse.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.toxicity"],
  },
  {
    id: "cf_patterns",
    nameKey: "garden.cards.cf_patterns.name",
    descriptionKey: "garden.cards.cf_patterns.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.patterns",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.pii", "garden.tags.regex", "garden.tags.dataProtection"],
  },
  {
    id: "cf_keywords",
    nameKey: "garden.cards.cf_keywords.name",
    descriptionKey: "garden.cards.cf_keywords.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.keywords",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.keywords", "garden.tags.blocklist"],
  },
  {
    id: "block_code_execution",
    nameKey: "garden.cards.block_code_execution.name",
    descriptionKey: "garden.cards.block_code_execution.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.codeSafety",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.code", "garden.tags.safety", "garden.tags.promptInjection"],
  },
  {
    id: "cf_competitor_intent",
    nameKey: "garden.cards.cf_competitor_intent.name",
    descriptionKey: "garden.cards.cf_competitor_intent.description",
    category: "litellm",
    subcategoryKey: "garden.subcategories.contentCategory",
    logo: litellmContentFilterLogo,
    tagKeys: ["garden.tags.contentCategory", "garden.tags.competitor", "garden.tags.topicBlocker"],
  },
];

export const PARTNER_GUARDRAIL_CARDS: GuardrailCardInfo[] = [
  {
    id: "presidio",
    nameKey: "garden.cards.presidio.name",
    descriptionKey: "garden.cards.presidio.description",
    category: "partner",
    logo: guardrailLogoMap["Presidio PII"],
    tagKeys: ["garden.tags.pii", "garden.tags.microsoft"],
    providerKey: "PresidioPII",
  },
  {
    id: "bedrock",
    nameKey: "garden.cards.bedrock.name",
    descriptionKey: "garden.cards.bedrock.description",
    category: "partner",
    logo: guardrailLogoMap["Bedrock Guardrail"],
    tagKeys: ["garden.tags.aws", "garden.tags.contentSafety"],
    providerKey: "Bedrock",
  },
  {
    id: "lakera",
    nameKey: "garden.cards.lakera.name",
    descriptionKey: "garden.cards.lakera.description",
    category: "partner",
    logo: guardrailLogoMap["Lakera"],
    tagKeys: ["garden.tags.security", "garden.tags.promptInjection"],
    providerKey: "Lakera",
  },
  {
    id: "openai_moderation",
    nameKey: "garden.cards.openai_moderation.name",
    descriptionKey: "garden.cards.openai_moderation.description",
    category: "partner",
    logo: guardrailLogoMap["OpenAI Moderation"],
    tagKeys: ["garden.tags.contentModeration", "garden.tags.openai"],
  },
  {
    id: "google_model_armor",
    nameKey: "garden.cards.google_model_armor.name",
    descriptionKey: "garden.cards.google_model_armor.description",
    category: "partner",
    logo: guardrailLogoMap["Google Cloud Model Armor"],
    tagKeys: ["garden.tags.googleCloud", "garden.tags.safety"],
  },
  {
    id: "guardrails_ai",
    nameKey: "garden.cards.guardrails_ai.name",
    descriptionKey: "garden.cards.guardrails_ai.description",
    category: "partner",
    logo: guardrailLogoMap["Guardrails AI"],
    tagKeys: ["garden.tags.openSource", "garden.tags.validation"],
  },
  {
    id: "zscaler",
    nameKey: "garden.cards.zscaler.name",
    descriptionKey: "garden.cards.zscaler.description",
    category: "partner",
    logo: guardrailLogoMap["Zscaler AI Guard"],
    tagKeys: ["garden.tags.enterprise", "garden.tags.security"],
  },
  {
    id: "panw",
    nameKey: "garden.cards.panw.name",
    descriptionKey: "garden.cards.panw.description",
    category: "partner",
    logo: guardrailLogoMap["PANW Prisma AIRS"],
    tagKeys: ["garden.tags.enterprise", "garden.tags.security"],
  },
  {
    id: "cisco_ai_defense",
    nameKey: "garden.cards.cisco_ai_defense.name",
    descriptionKey: "garden.cards.cisco_ai_defense.description",
    category: "partner",
    logo: guardrailLogoMap["Cisco AI Defense"],
    tagKeys: ["garden.tags.enterprise", "garden.tags.security", "garden.tags.promptInjection", "garden.tags.pii"],
    providerKey: "CiscoAiDefense",
  },
  {
    id: "noma",
    nameKey: "garden.cards.noma.name",
    descriptionKey: "garden.cards.noma.description",
    category: "partner",
    logo: guardrailLogoMap["Noma Security"],
    tagKeys: ["garden.tags.security", "garden.tags.threatDetection"],
  },
  {
    id: "aporia",
    nameKey: "garden.cards.aporia.name",
    descriptionKey: "garden.cards.aporia.description",
    category: "partner",
    logo: guardrailLogoMap["Aporia AI"],
    tagKeys: ["garden.tags.hallucination", "garden.tags.policy"],
  },
  {
    id: "aim",
    nameKey: "garden.cards.aim.name",
    descriptionKey: "garden.cards.aim.description",
    category: "partner",
    logo: guardrailLogoMap["AIM Guardrail"],
    tagKeys: ["garden.tags.security", "garden.tags.threatDetection"],
  },
  {
    id: "cato_networks",
    nameKey: "garden.cards.cato_networks.name",
    descriptionKey: "garden.cards.cato_networks.description",
    category: "partner",
    logo: guardrailLogoMap["Cato Networks Guardrail"],
    tagKeys: ["garden.tags.security", "garden.tags.threatDetection"],
  },
  {
    id: "prompt_security",
    nameKey: "garden.cards.prompt_security.name",
    descriptionKey: "garden.cards.prompt_security.description",
    category: "partner",
    logo: guardrailLogoMap["Prompt Security"],
    tagKeys: ["garden.tags.promptInjection", "garden.tags.security"],
  },
  {
    id: "lasso",
    nameKey: "garden.cards.lasso.name",
    descriptionKey: "garden.cards.lasso.description",
    category: "partner",
    logo: guardrailLogoMap["Lasso Guardrail"],
    tagKeys: ["garden.tags.contentModeration"],
  },
  {
    id: "pangea",
    nameKey: "garden.cards.pangea.name",
    descriptionKey: "garden.cards.pangea.description",
    category: "partner",
    logo: guardrailLogoMap["Pangea Guardrail"],
    tagKeys: ["garden.tags.compliance", "garden.tags.security"],
  },
  {
    id: "enkryptai",
    nameKey: "garden.cards.enkryptai.name",
    descriptionKey: "garden.cards.enkryptai.description",
    category: "partner",
    logo: guardrailLogoMap["EnkryptAI"],
    tagKeys: ["garden.tags.enterprise", "garden.tags.governance"],
  },
  {
    id: "javelin",
    nameKey: "garden.cards.javelin.name",
    descriptionKey: "garden.cards.javelin.description",
    category: "partner",
    logo: guardrailLogoMap["Javelin Guardrails"],
    tagKeys: ["garden.tags.gateway", "garden.tags.security"],
  },
  {
    id: "pillar",
    nameKey: "garden.cards.pillar.name",
    descriptionKey: "garden.cards.pillar.description",
    category: "partner",
    logo: guardrailLogoMap["Pillar Guardrail"],
    tagKeys: ["garden.tags.monitoring", "garden.tags.safety"],
  },
  {
    id: "akto",
    nameKey: "garden.cards.akto.name",
    descriptionKey: "garden.cards.akto.description",
    category: "partner",
    logo: guardrailLogoMap["Akto"],
    tagKeys: ["garden.tags.security", "garden.tags.safety", "garden.tags.monitoring"],
  },
  {
    id: "promptguard",
    nameKey: "garden.cards.promptguard.name",
    descriptionKey: "garden.cards.promptguard.description",
    category: "partner",
    logo: guardrailLogoMap["PromptGuard"],
    tagKeys: ["garden.tags.security", "garden.tags.promptInjection", "garden.tags.pii"],
    providerKey: "Promptguard",
    eval: {
      f1: 94.9,
      precision: 100.0,
      recall: 90.4,
      testCases: 5384,
      latency: "~150ms",
    },
  },
  {
    id: "xecguard",
    nameKey: "garden.cards.xecguard.name",
    descriptionKey: "garden.cards.xecguard.description",
    category: "partner",
    logo: guardrailLogoMap["XecGuard"],
    tagKeys: ["garden.tags.security", "garden.tags.policy", "garden.tags.grounding", "garden.tags.rag"],
    providerKey: "Xecguard",
  },
  {
    id: "deepkeep",
    nameKey: "garden.cards.deepkeep.name",
    descriptionKey: "garden.cards.deepkeep.description",
    category: "partner",
    logo: guardrailLogoMap["DeepKeep AI Firewall"],
    tagKeys: ["garden.tags.security", "garden.tags.promptInjection", "garden.tags.pii", "garden.tags.firewall"],
    providerKey: "Deepkeep",
  },
  {
    id: "repelloai",
    nameKey: "garden.cards.repelloai.name",
    descriptionKey: "garden.cards.repelloai.description",
    category: "partner",
    logo: guardrailLogoMap["RepelloAI Argus"],
    tagKeys: ["garden.tags.security", "garden.tags.policy", "garden.tags.promptInjection"],
    providerKey: "Repelloai",
  },
  {
    id: "straiker",
    nameKey: "garden.cards.straiker.name",
    descriptionKey: "garden.cards.straiker.description",
    category: "partner",
    logo: guardrailLogoMap["Straiker"],
    tagKeys: [
      "garden.tags.agentic",
      "garden.tags.promptInjection",
      "garden.tags.toolMisuse",
      "garden.tags.mcp",
      "garden.tags.skills",
    ],
    providerKey: "Straiker",
  },
  {
    id: "alice",
    nameKey: "garden.cards.alice.name",
    descriptionKey: "garden.cards.alice.description",
    category: "partner",
    logo: guardrailLogoMap["Alice"],
    tagKeys: ["garden.tags.contentModeration", "garden.tags.promptInjection", "garden.tags.pii", "garden.tags.policy"],
    providerKey: "Alice",
  },
  {
    id: "conduct",
    nameKey: "garden.cards.conduct.name",
    descriptionKey: "garden.cards.conduct.description",
    category: "partner",
    logo: guardrailLogoMap["Conduct Guard"],
    tagKeys: ["garden.tags.security", "garden.tags.promptInjection", "garden.tags.pii", "garden.tags.policy"],
    providerKey: "Conduct",
  },
];

export const ALL_CARDS = [...LITELLM_CONTENT_FILTER_CARDS, ...PARTNER_GUARDRAIL_CARDS];
